name = "iris"
srcDir = "./src/"
defaultTargets = ["Iris", "Bluebell", "IrisTest"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.26.0"

[[lean_lib]]
name = "Iris"
globs = ["Iris.*"]

[[lean_lib]]
name = "Bluebell"
globs = ["Bluebell.*"]

[[lean_lib]]
name = "IrisTest"
globs = ["Iris.*"]
